__program__ = 'fairy'
__version__ = 'v4.1.1'
__author__ = 'Eric Davis, Brian Hartvigsen, Joshua Crowgey, engao'
__API_CLIENT_ID__ = '803716979682-oarojlif8nragfe60scgdero8h1su90j.apps.googleusercontent.com'
__API_CLIENT_SECRET__ = 'a_zY5XBVEwETyk2IkrUUaFa1'